### ISSUE TITLE
make doc-pdf fails

### ISSUE THREAD

**Issue by t-b** [ome/ome-files-cpp#35]
I've compiled ome-files-cpp on my debian jessie machine.
The creation of the pdf manual was not successfull, this stopped the build process.
See [make-doc.txt](https://github.com/ome/ome-files-cpp/files/527673/make-doc.txt) for the build log.

```
$doxygen --version
1.8.13
$sphinx-build --version
Sphinx (sphinx-build) 1.5a1
```

**Comment by rleigh-codelibre** [comment]
The TeX Gyre fonts are not in your fontconfig configuration.  You'll need to add them and then run `fc-cache -frsv`.  After that, they will be picked up.  You should have a sample file in `texmf-var/fonts/conf/texlive-fontconfig.conf` (under your texlive install location).  Copy this to e.g. `/etc/fonts/conf.d/09-texlive.conf` and edit to fix the paths if needed before running `fc-cache`.  I think this happens automatically when running the Debian-provided TeXLive, but not when using the upstream installer.

For this and other reasons, we will likely be dropping the PDF manual at some point in the near future in favour of the HTML documentation.  Note that you can disable building the PDF when running CMake with the `-Dsphinx-pdf=OFF` option (see the end of `cmake/Options.cmake`.

We would also like to add debian/ubuntu packaging in the future as well, which will make building it easier.  We don't have a deadline for this, but making ome-files easy to build and use is something we do have in mind.

I hope that's useful.  Please do get back in touch if you have any other questions about this or anything else ome-files-related.


Kind regards,
Roger

**Comment by t-b** [comment]
@rleigh-codelibre Thanks for the latex fonts reminder. I've followed your description and now it works.
