### ISSUE TITLE
Version.h gets stale on branch switch

### ISSUE THREAD

**Issue by t-b** [ome/ome-files-cpp#52]
Consider the following steps:
- `git clone git@github.com:ome/ome-files-cpp.git`
- `mkdir build`
- `cd build`
- `cmake ..`
- `make`
-  `grep OME_FILES_VCS_SHORTREVISION lib/ome/files/Version.h`
#define OME_FILES_VCS_SHORTREVISION "3a25964"

Now if you change branches in the repo which has a different HEAD commit and rebuild with make and call `grep OME_FILES_VCS_SHORTREVISION lib/ome/files/Version.h` again the output has not changed.

A fix could be to regenerate Version.h at every make invocation.

**Comment by rleigh-codelibre** [comment]
Thanks for the suggestion.  The logic at present copes if the root CMakeLists.txt is changed (or any other cmake logic or dependent files) which would trigger a cmake rerun, but not if the branch switch doesn't change anything.  At least on our own build infrastructure, we always build from a clean slate, so don't encounter this problem directly.

I'll see if it's possible to regenerate only if changed, if it's not too expensive (invoking git and not forcing a rebuild of everything).  There's also the issue of what a significant branch switch means; change of HEAD tree hash, change of head, what about dirty uncommitted state?  In general, we've kept the underlying version control as uncoupled as possible from the code (the hash here is purely informational and would be blank if building from a source release were it not provided separately).

In general, I'd suggest that you should re-run cmake or start with a fresh build directory after a branch switch, to be sure of a clean and consistent state.


Regards,
Roger

**Comment by t-b** [comment]
Thanks roger for the detailed explanation.

**Comment by rleigh-codelibre** [comment]
By the way, the latest releases (>=0.3.0) dropped the complex getting of the various versions from git; it's now hardcoded in the root `CmakeLists.txt`, so this will result in an automatic rerun when the branch switch is between versions.  The only autogenerated bit is

`#define OME_FILES_VERSION_EXTRA_S "@OME_VCS_DEV@"` which is only set for untagged development builds.

So this will only not be regenerated when switching branches for the same development version.  Not 100% perfect, but will regenerate in most typical cases now.

**Comment by sbesson** [comment]
Assuming the suggestions from https://github.com/ome/ome-files-cpp/issues/52#issuecomment-278033762 together with the versioning improvements since 0.3.0 address most of  this issue, closing.
